//Download by http://www.NewXing.com
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Nethief.rc
//
#define ID_OK                           1
#define IDD_ABOUTBOX                    100
#define IDD_TIPOFTHEDAY                 101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDB_SPLASH                      131
#define IDD_SPLASH                      131
#define IDI_LIGHT                       142
#define IDD_COMMUNITY                   143
#define IDI_FILEMANAGER                 143
#define IDI_PROGRAM                     151
#define IDI_PARAMETER                   152
#define IDI_FINDFILE                    153
#define IDI_PROPERTY                    154
#define IDI_OFFLINE                     155
#define IDR_CONSOLETOOLBAR              156
#define IDI_BUSY                        156
#define IDR_FILETOOLBAR                 157
#define IDI_SYSTRAY                     157
#define IDB_CONSOLETOOLBAR              158
#define IDI_SYSTRAY1                    158
#define IDB_FILETOOLBAR                 159
#define IDD_TOOLBARRUN                  160
#define IDR_NETTOOLBAR                  160
#define IDD_TOOLBARFINDFILE             161
#define IDD_TOOLBARPROPERTY_SINGLE      162
#define IDD_TOOLBARPROPERTY_MULTI       163
#define IDD_TOOLBARPROPERTY_DISKDRIVE   164
#define IDR_SYSTRAYMENU                 164
#define IDB_NETTOOLBAR                  165
#define IDR_POPUPMENU                   165
#define IDB_WIZARD                      169
#define IDD_WIZARD2                     170
#define IDD_WIZARD1                     171
#define IDD_WIZARD4                     172
#define IDD_WIZARD5                     174
#define IDD_TOOLBARBUILDSERVER          175
#define IDD_HELPUPDATE                  176
#define IDI_EXPORT                      177
#define IDC_CURSOR_HAND                 178
#define IDD_TOOLBARRUN_REMOTE           178
#define IDR_ONLINE                      179
#define IDD_TOOLBARFINDFILE_RESULT      179
#define IDR_GLOBAL                      180
#define IDD_OPTION                      180
#define IDR_SYSTEM                      181
#define IDD_EASTEREGG                   181
#define IDD_WIZARD3                     182
#define IDD_SELECTIP                    183
#define IDI_MODE                        184
#define IDD_WIZARD6                     184
#define IDI_VIEW                        185
#define IDI_KEYNAME                     186
#define IDI_FILENAME                    187
#define IDI_NOTE                        190
#define IDB_LOGO                        191
#define IDI_MYCOMPUTER                  191
#define IDI_FOLDER                      192
#define IDI_FOLDER_OPEN                 193
#define IDI_REMOTEHOST                  194
#define IDI_REMOTEHOST_DISCONNECT       195
#define IDB_LOGO1                       196
#define IDI_DRIVE_REMOVABLE             196
#define IDI_DRIVE_FIXED                 197
#define IDB_NETTOOLBAR_HOT              197
#define IDI_DRIVE_CDROM                 198
#define IDB_FILETOOLBAR_HOT             198
#define IDI_DRIVE_ZIP                   199
#define IDB_CONSOLETOOLBAR_HOT          199
#define IDI_DRIVE_REMOTE                200
#define IDI_LARGE_DRIVE_REMOVABLE       201
#define IDI_LARGE_DRIVE_FIXED           202
#define IDI_LARGE_DRIVE_CDROM           203
#define IDI_LARGE_DRIVE_ZIP             204
#define IDI_LARGE_DRIVE_REMOTE          205
#define IDI_REMOTEHOST_HTTPTUNNEL       206
#define IDI_REMOTEHOST_HTTPTUNNEL_DISCONNECT 207
#define IDI_SELECTIP                    208
#define IDI_ADAPTER                     209
#define IDD_SELECTFILEOPERATION         210
#define IDI_SELECTFILEOPERATION         211
#define IDD_REMARK                      211
#define IDI_UNKNOWNFILE                 212
#define IDD_WIZARD31                    212
#define IDD_DOWNLOAD                    213
#define IDI_URL                         213
#define IDB_CUTLINE                     216
#define IDB_CUTLINE1                    217
#define IDC_EDIT_URL                    1000
#define IDC_EDIT1                       1008
#define IDC_BUTTON_README               1009
#define IDC_BUTTON1                     1009
#define IDC_STATIC_LIGHT                1010
#define IDC_EDIT2                       1010
#define IDC_BUTTON2                     1011
#define IDC_LIST1                       1012
#define IDC_EDIT_FILENAME               1013
#define IDC_EDIT_NOTE                   1014
#define IDC_BUTTON_BROWSE               1015
#define IDC_CHECK_HIDE                  1018
#define IDC_CHECK_ARCHIVE               1019
#define IDC_CHECK_SYSTEM                1020
#define IDC_STATIC_ICON                 1021
#define IDC_STATIC_SIZE                 1023
#define IDC_STATIC_TYPE                 1025
#define IDC_STATIC_CTIME                1026
#define IDC_STATIC_MTIME                1027
#define IDC_STATIC_ATIME                1028
#define IDC_CHECK_READONLY              1029
#define IDC_STATIC_STATISTIC            1030
#define IDC_STATIC_SERIALNUMBER         1031
#define IDC_STATIC_USED                 1032
#define IDC_STATIC_UNUSED               1033
#define IDC_STATIC_TOTAL                1034
#define IDC_STATIC_USED_PERCENT         1035
#define IDC_STATIC_UNUSED_PERCENT       1036
#define IDC_STATIC_TOTAL_PERCENT        1037
#define IDC_EDIT_USERNAME               1051
#define IDC_EDIT_PASSWORD               1052
#define IDC_EDIT_PASSWORD2              1053
#define IDC_EDIT_SERVERFILENAME         1057
#define IDC_BUTTON_BUILD                1058
#define IDC_STATIC_HOSTNAME             1059
#define IDC_EDIT_KEYNAME                1059
#define IDC_STATIC_IPADDRESS            1060
#define IDC_STATIC_POSITION             1061
#define IDC_STATIC_ONLINENUM            1062
#define IDC_EDIT_ADDRESS                1064
#define IDC_EDIT_PATH                   1065
#define IDC_EDIT_CALLBOARD              1067
#define IDC_EDIT_HOMEPAGE               1067
#define IDC_STATIC_VERSION              1069
#define IDC_STATIC_DATE                 1070
#define IDC_STATIC_HOMEPAGE             1071
#define IDC_STATIC_EMAIL                1072
#define IDC_STATIC_NEWVERSION           1073
#define IDC_STATIC_NEWDATE              1074
#define IDC_STATIC_NOTE                 1075
#define IDC_COMBO1                      1077
#define IDC_EDIT_VIEWERFILENAME         1079
#define IDC_STATIC1                     1080
#define IDC_EDIT_FILENAME1              1081
#define IDC_EDIT_FILENAME2              1082
#define IDC_EDIT_FILENAME3              1083
#define IDC_CHECK_SELECTIP              1084
#define IDC_STATIC_CHATROOM             1085
#define IDC_EDIT_TEST                   1086
#define IDC_BUTTON_TEST                 1087
#define IDC_BUTTON_OVERLAY              1088
#define IDC_BUTTON_CONTINUE             1089
#define IDC_STATIC_FILENAME             1090
#define IDC_STATIC_SOURCEICON           1091
#define IDC_STATIC_SOURCEFILEINFO       1092
#define IDC_STATIC_DESTICON             1093
#define IDC_STATIC_DESTFILEINFO         1094
#define IDC_EDIT                        1095
#define IDC_EDIT_FILENAME4              1096
#define IDC_BUTTON_UPDATE               1097
#define IDC_BUTTON_HOMEPAGE             16898
#define IDC_BUTTON_EMAIL                16899
#define IDC_BUTTON_TIPS                 16901
#define IDC_CHECK1                      16903
#define IDC_STATIC_TIPS                 16905
#define IDC_STATIC_BACKGROUND           16908
#define IDC_STATIC_DOYOUKNOW            16910
#define ID_HELP_TIPOFTHEDAY             32771
#define ID_TOOLBAR_FILEMANAGER          32772
#define ID_TOOLBAR_COMMUNITY            32773
#define ID_TOOLBAR_BACK                 32774
#define ID_TOOLBAR_REFRESH              32775
#define ID_TOOLBAR_FINDFILE             32776
#define ID_TOOLBAR_CUT                  32777
#define ID_TOOLBAR_COPY                 32778
#define ID_TOOLBAR_PASTE                32779
#define ID_TOOLBAR_VIEW                 32780
#define ID_TOOLBAR_DELETE               32781
#define ID_TOOLBAR_PROPERTY             32782
#define ID_TOOLBAR_NEWFILE              32783
#define ID_TOOLBAR_NEWFOLDER            32784
#define ID_TOOLBAR_RUN                  32785
#define ID_MENU_FILE_RUN                32786
#define ID_MENU_FILE_RENAME             32787
#define ID_MENU_CONSOLE_TAB             32789
#define ID_TOOLBAR_SELECTALL            32791
#define ID_TOOLBAR_REVERSESELECT        32792
#define ID_SYSTRAYMENU_WINDOW           32793
#define ID_MENU_CONSOLE_LOGON           32796
#define ID_SYSTRAYMENU_HIDE             32797
#define ID_TOOLBAR_DELETEHOST           32799
#define ID_TOOLBAR_BUILDSERVER          32800
#define ID_HELP_README                  32802
#define ID_HELP_HOMEPAGE                32803
#define ID_HELP_EMAIL                   32804
#define ID_HELP_UPDATE                  32805
#define ID_TOOLBAR_DISCONNECT           32807
#define ID_TOOLBAR_STOP                 32808
#define ID_MENU_NET_OPTION              32809
#define ID_MENU_NET_UNINSTALL           32811
#define ID_MENU_NET_NOTE                32812
#define ID_POPUPMENU_COPY               32813
#define ID_POPUPMENU_ADD                32814
#define ID_POPUPMENU_REMARK             32815
#define ID_MENU_NET_DOWNLOAD            32816
#define ID_INDICATOR_PROGRESS           61204
#define ID_INDICATOR_OFFLINE            61205
#define ID_INDICATOR_BUSY               61206

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
